package com.example.auradesktop.services;

import com.itextpdf.io.font.PdfEncodings;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.events.Event;
import com.itextpdf.kernel.events.IEventHandler;
import com.itextpdf.kernel.events.PdfDocumentEvent;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.geom.Rectangle;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfPage;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.PdfCanvas;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.AreaBreakType;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class PdfReportService {

    public static void createReport(File destFile, String patientName, String diagnosisText) throws Exception {
        PdfWriter writer = new PdfWriter(destFile);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf, PageSize.A4);
        document.setMargins(50, 50, 50, 50);

        // Load Font
        String FONT = "C:/Windows/Fonts/arial.ttf";
        PdfFont font;
        try {
             font = PdfFontFactory.createFont(FONT, PdfEncodings.IDENTITY_H);
        } catch (Exception e) {
             font = PdfFontFactory.createFont();
        }
        PdfFont boldFont;
        try {
            boldFont = PdfFontFactory.createFont("C:/Windows/Fonts/arialbd.ttf", PdfEncodings.IDENTITY_H);
        } catch (Exception e) {
            boldFont = font;
        }

        // --- COVER PAGE ---
        
        // Background Logo for Cover
        try {
            Image logo = new Image(ImageDataFactory.create(
                    PdfReportService.class.getResource("/com/example/auradesktop/Images/1.png")));
            // Full page background
            logo.setFixedPosition(0, 0);
            logo.scaleToFit(PageSize.A4.getWidth(), PageSize.A4.getHeight());
            logo.setOpacity(0.15f); 
            document.add(logo);
        } catch (Exception ignored) {}

        document.add(new Paragraph("\n\n\n\n\n")); // Spacer

        // Hospital / App Name
        document.add(new Paragraph("AURA HEALTH COMPANION")
                .setFont(boldFont).setFontSize(14).setFontColor(ColorConstants.GRAY)
                .setTextAlignment(TextAlignment.CENTER));

        document.add(new Paragraph("\n"));

        // Main Title
        document.add(new Paragraph("CONFIDENTIAL MEDICAL REPORT")
                .setFont(boldFont).setFontSize(26).setFontColor(new DeviceRgb(8, 120, 242)) // Aura Blue
                .setTextAlignment(TextAlignment.CENTER));

        document.add(new Paragraph("Radiology AI Analysis")
                .setFont(font).setFontSize(16).setFontColor(ColorConstants.DARK_GRAY)
                .setTextAlignment(TextAlignment.CENTER));

        document.add(new Paragraph("\n\n\n"));

        // Patient Info Table
        Table infoTable = new Table(UnitValue.createPercentArray(new float[]{1, 2}));
        infoTable.setWidth(UnitValue.createPercentValue(80));
        infoTable.setHorizontalAlignment(com.itextpdf.layout.properties.HorizontalAlignment.CENTER);

        addInfoRow(infoTable, "Patient Name:", patientName, boldFont, font);
        addInfoRow(infoTable, "Patient ID:", "100" + (System.currentTimeMillis() % 10000), boldFont, font); // Pseudo-ID
        addInfoRow(infoTable, "Date:", LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")), boldFont, font);
        addInfoRow(infoTable, "Referred By:", "Dr. John Doe", boldFont, font); // Placeholder
        addInfoRow(infoTable, "Modality:", "X-Ray / Medical Imaging", boldFont, font);

        document.add(infoTable);

        document.add(new Paragraph("\n\n\n\n\n")); // Spacer at bottom

        document.add(new Paragraph("Generated by Aura AI Diagnostics")
                .setFont(font).setFontSize(10).setItalic().setFontColor(ColorConstants.GRAY)
                .setTextAlignment(TextAlignment.CENTER));

        // --- END COVER PAGE ---
        document.add(new AreaBreak(AreaBreakType.NEXT_PAGE));

        // --- CONTENT PAGES ---
        
        // Add Header/Footer Event for subsequent pages
        pdf.addEventHandler(PdfDocumentEvent.END_PAGE, new PageHeaderFooter(font));

        document.add(new Paragraph("Detailed Findings")
                .setFont(boldFont).setFontSize(18).setUnderline()
                .setFontColor(new DeviceRgb(8, 120, 242)));
        
        document.add(new Paragraph("\n"));

        // Render Report Content
        // Handle Gemini formatting: Remove ** for bold, convert to upper case sections, etc.
        // Assuming details come with headers like "1. FINDINGS", we can just print nicely.
        String[] lines = diagnosisText.split("\n");
        for (String line : lines) {
            line = line.trim();
            if (line.isEmpty()) {
                document.add(new Paragraph("\n")); // Preserve spacing
                continue;
            }

            // Check if line looks like a header (e.g., "1. FINDINGS" or "IMPRESSION:")
            if (line.matches("(?i)^(?:\\d+\\.\\s*)?[A-Z][A-Z\\s]+[:]?.*")) {
                document.add(new Paragraph(line.replace("**", ""))
                        .setFont(boldFont).setFontSize(12)
                        .setMarginTop(10).setMarginBottom(5));
            } else {
                // Regular body text
                document.add(new Paragraph(line.replace("**", "").replace("* ", "\u2022 "))
                        .setFont(font).setFontSize(11)
                        .setTextAlignment(TextAlignment.JUSTIFIED)
                        .setMultipliedLeading(1.5f)); // 1.5 spacing
            }
        }

        // Disclaimer at the very end
        document.add(new Paragraph("\n\n"));
        document.add(new Paragraph("DISCLAIMER: This report is generated by an Artificial Intelligence system. It is intended to assist medical professionals and should NOT be used as a definitive diagnosis. Please consult a certified radiologist.")
                .setFont(font).setFontSize(9).setItalic().setFontColor(ColorConstants.RED)
                .setTextAlignment(TextAlignment.JUSTIFIED)
                .setBackgroundColor(new DeviceRgb(255, 240, 240))
                .setPadding(10));

        document.close();
    }

    private static void addInfoRow(Table table, String label, String value, PdfFont boldFont, PdfFont font) {
        table.addCell(new Cell().add(new Paragraph(label).setFont(boldFont)).setBorder(com.itextpdf.layout.borders.Border.NO_BORDER).setPadding(5));
        table.addCell(new Cell().add(new Paragraph(value).setFont(font)).setBorder(com.itextpdf.layout.borders.Border.NO_BORDER).setPadding(5));
    }

    // Inner Class for Header/Footer
    private static class PageHeaderFooter implements IEventHandler {
        PdfFont font;
        public PageHeaderFooter(PdfFont font) { this.font = font; }

        @Override
        public void handleEvent(Event event) {
            PdfDocumentEvent docEvent = (PdfDocumentEvent) event;
            PdfDocument pdf = docEvent.getDocument();
            PdfPage page = docEvent.getPage();
            // Skip Cover Page (Page 1)
            int pageNumber = pdf.getPageNumber(page);
            if (pageNumber == 1) return;

            Rectangle pageSize = page.getPageSize();
            PdfCanvas canvas = new PdfCanvas(page.newContentStreamBefore(), page.getResources(), pdf);

            // Header: Date + Confidential
            canvas.beginText().setFontAndSize(font, 9).setFillColor(ColorConstants.GRAY)
                    .moveText(pageSize.getLeft() + 50, pageSize.getTop() - 30)
                    .showText("Aura Health Companion - Confidential Report")
                    .moveText(pageSize.getWidth() - 250, 0) // rough shift right
                    .showText("Date: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")))
                    .endText();

            // Draw Footer: Page X
            canvas.beginText().setFontAndSize(font, 9).setFillColor(ColorConstants.BLACK)
                    .moveText(pageSize.getWidth() / 2 - 20, pageSize.getBottom() + 30)
                    .showText("Page " + pageNumber)
                    .endText();
            
            canvas.release();
        }
    }
}
